### ISSUE TITLE
[BUG] KeyError when enabling kill switch

### ISSUE THREAD

**Issue by RememberTheAir** [ProtonVPN/protonvpn-cli-ng#109] opened 2020-02-07 20:38 UTC
**Describe the bug**
`KeyError` when enabling kill switch (with "allow access to/from LAN")

**To Reproduce**
1. `sudo protonvpn configure`
2. select option 5: _Kill Switch_
3. select option 2: _enable kill switch (allow access to/from LAN)_

**Expected behavior**
No exception is raised

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
```bash
pi@raspberrypi:~ $ sudo protonvpn configure
What do you want to change?

1) Username and Password
2) ProtonVPN Plan
3) Default Protocol
4) DNS Management
5) Kill Switch
6) Split Tunneling
7) Purge Configuration

Please enter your choice or leave empty to quit: 5

The Kill Switch will block all network traffic
if the VPN connection drops unexpectedly.

Please note that the Kill Switch assumes only one network interface being active.

1) Enable Kill Switch (Block access to/from LAN)
2) Enable Kill Switch (Allow access to/from LAN)
3) Disable Kill Switch

Please enter your choice or leave empty to quit: 2
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/local/lib/python3.6/site-packages/protonvpn_cli/cli.py", line 143, in cli
    configure_cli()
  File "/usr/local/lib/python3.6/site-packages/protonvpn_cli/cli.py", line 340, in configure_cli
    set_killswitch()
  File "/usr/local/lib/python3.6/site-packages/protonvpn_cli/cli.py", line 590, in set_killswitch
    if killswitch and int(get_config_value("USER", "split_tunnel")):
  File "/usr/local/lib/python3.6/site-packages/protonvpn_cli/utils.py", line 122, in get_config_value
    return config[group][key]
  File "/usr/local/lib/python3.6/configparser.py", line 1230, in __getitem__
    raise KeyError(key)
KeyError: 'split_tunnel'
pi@raspberrypi:~ $ sudo protonvpn --v
ProtonVPN-CLI v2.2.1
pi@raspberrypi:~ $
```

**Desktop (please complete the following information):**
 - OS: Raspbian 9 (Stretch)
 - Python Version: 3.6
 - ProtonVPN-CLI Version: 2.2.1

**Additional context**

Even though protonvpn-cl raises an exception, the kill switch is correctly enabled.

I was connected to a p2p server when this happened

**Comment by Rafficer** [comment] 2020-02-07 20:41
Thank you for reporting this. This is a duplicate of #101, which is why I'll close this issue. A fix will be published with the next release.

To temporarily fix this do the following:

1. `sudo protonvpn configure`
2. Select Split Tunneling (`6`)
3. `n` to "disable Split Tunneling?"
4. `n` to "remove split tunneling configuration?"

After that you can enable the Kill Switch.

**Closed by Rafficer** 2020-02-07 20:41 UTC

**Comment by RememberTheAir** [comment] 2020-02-08 12:23
Thank you and sorry for the duplicate!
