### ISSUE TITLE
[BUG] Cannot enable kill switch

### ISSUE THREAD

**Issue by Detrous** [ProtonVPN/protonvpn-cli-ng#113] opened 2020-02-09 21:16 UTC
**Describe the bug**
Cannot enable kill switch.

**To Reproduce**
1. Setup proton vpn via sudo protonvpn init
2. Enable kill switch as described here: https://protonvpn.com/support/linux-vpn-tool/ 
3. See an error

**Expected behavior**
Enable Kill Switch

**Error Messages:**
```Traceback (most recent call last):
  File "/usr/local/bin/protonvpn", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/cli.py", line 143, in cli
    configure_cli()
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/cli.py", line 340, in configure_cli
    set_killswitch()
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/cli.py", line 590, in set_killswitch
    if killswitch and int(get_config_value("USER", "split_tunnel")):
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/utils.py", line 122, in get_config_value
    return config[group][key]
  File "/usr/lib/python3.7/configparser.py", line 1251, in __getitem__
    raise KeyError(key)
KeyError: 'split_tunnel'
```

**Desktop:**
 - OS: Ubuntu 19.04
 - Python Version: 3.7.5
 - ProtonVPN-CLI Version: v2.2.1

**Comment by Detrous** [comment] 2020-02-09 21:29
I found solution.
I think problem in https://protonvpn.com/support/linux-vpn-tool/
If enable "Split Tunneling" and then enable "Kill Switch" - all works

**Comment by enderwiggens** [comment] 2020-02-10 04:22
I just ran into this issue as well.

**Comment by enderwiggens** [comment] 2020-02-10 04:28
O

> I found solution.
> I think problem in https://protonvpn.com/support/linux-vpn-tool/
> If enable "Split Tunneling" and then enable "Kill Switch" - all works

This worked for me as well.

**Comment by Rafficer** [comment] 2020-02-10 06:48
This is a duplicate of #101. Fix is already pushed and merged, just waiting for release now.

I'll leave this up now until the fix is released. For anyone coming across, here's how to fix it for you:


> 1. `sudo protonvpn configure`
> 2. Select Split Tunneling (`6`)
> 3. `n` to "disable Split Tunneling?"
> 4. `n` to "remove split tunneling configuration?"
> 
> After that you can enable the Kill Switch.

**Comment by Rafficer** [comment] 2020-02-12 15:19
As the new Version (v2.2.2) has now been released, I'll close this :)

**Closed by Rafficer** 2020-02-12 15:19 UTC
