### ISSUE TITLE
[BUG] Auto-connect not working

### ISSUE THREAD

**Issue by pszucs** [ProtonVPN/protonvpn-cli-ng#36] opened 2019-11-21 20:02 UTC
**Describe the bug**
I followed the [instructions](https://github.com/ProtonVPN/protonvpn-cli-ng/blob/master/USAGE.md#auto-connect-on-boot) to set up auto-connecting on boot but it doesn't work.

Manually connecting to the server works.

**To Reproduce**
1. Follow the steps above and set up auto-connect on boot
2. Restart computer
3. Check IP address

**Expected behavior**
I was expecting the client to auto-connect to the provided server, but it didn't, I've got the IP from my ISP instead of the VPN server's IP.

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**

Output of the relevant section of ~/.pvpn-cli/pvpn-cli.log

2019-11-21 19:44:20,359 — protonvpn-cli — DEBUG — cli:84 — ###########################
2019-11-21 19:44:20,360 — protonvpn-cli — DEBUG — cli:85 — ### NEW PROCESS STARTED ###
2019-11-21 19:44:20,360 — protonvpn-cli — DEBUG — cli:86 — ###########################
2019-11-21 19:44:20,361 — protonvpn-cli — DEBUG — cli:87 — ['/usr/local/bin/protonvpn', 'connect', 'UK#6', '-p', 'UDP']
2019-11-21 19:44:20,361 — protonvpn-cli — DEBUG — cli:88 — Arguments
{'--cc': None,
 '--fastest': False,
 '--help': False,
 '--p2p': False,
 '--random': False,
 '--sc': False,
 '--tor': False,
 '--version': False,
 '-p': 'UDP',
 '<servername>': 'UK#6',
 'c': False,
 'configure': False,
 'connect': True,
 'd': False,
 'disconnect': False,
 'examples': False,
 'init': False,
 'r': False,
 'reconnect': False,
 'refresh': False,
 's': False,
 'status': False}
2019-11-21 19:44:20,361 — protonvpn-cli — DEBUG — cli:89 — USER: peter
2019-11-21 19:44:20,361 — protonvpn-cli — DEBUG — cli:90 — CONFIG_DIR: /home/peter/.pvpn-cli
2019-11-21 19:44:20,380 — protonvpn-cli — DEBUG — direct:226 — Starting direct connect with UK#6
2019-11-21 19:44:20,381 — protonvpn-cli — DEBUG — call_api:30 — Initiating API Call: https://api.protonmail.ch/vpn/logicals
2019-11-21 19:44:20,386 — protonvpn-cli — DEBUG — call_api:40 — Error connecting to ProtonMail API

**Desktop (please complete the following information):**
 - OS: elementary OS
 - Python Version: 3.6.8
 - ProtonVPN-CLI Version: 2.1.1

**Comment by Rafficer** [comment] 2019-11-21 20:23
This is basically a duplicate of the issues in #10.

The problem is that the program fires before you have a working internet connection. I plan to add a "waiting for connection" feature this weekend and it should be resolved with the next release.

I'll close this issue, please refer to #10.

**Closed by Rafficer** 2019-11-21 20:23 UTC

**Comment by pszucs** [comment] 2019-11-21 21:09
Awesome, thanks (sorry for the duplicate).
